POST http://localhost/519_anteater_express/server/public/api/admin-lines-buses.php

{
  "gap": ['1100', '1200'],
  "gapDuration": ['5', '5']
}

###

GET http://localhost/519_anteater_express/server/public/api/admin-lines-buses.php

###

GET http://localhost/519_anteater_express/server/public/api/admin-lines-buses-sessions.php
#get sessions
